### ISSUE TITLE
GoodReporter.stop not doing anything

### ISSUE THREAD

**Issue by yonjah** [hapijs/good-reporter#24]
Looking at the code it seems like the `stop` method isn't doing anything.
While the `start` method actually binds the listener on the `emitter`.
https://github.com/hapijs/good-reporter/blob/master/lib/index.js#L53
so calling 
```javascript
reporter.start(emitter,  callback);
reporter.stop();
reporter.start(emitter,  callback);
```
Will result in multiple calls to the reporter for the same events.

**Comment by arb** [comment]
The base `stop` method does indeed do nothing. It's up to the individual implementors to decide what the `stop` method should be doing and overwrite is accordingly. That would include things like closing open DB connections, flushing any events to storage, etc.

**Comment by yonjah** [comment]
then shouldn't it be up to the implementor to bind listen events in the `start` method ?
or maybe instead of start it should be called `init` I just think having a `stop` action that is not the opposite and actually completely irrelevant to the start its counter intuitive.

As you can see from other reporter implementations  like (good-console)[https://github.com/hapijs/good-console] it doesn't implement the `stop` method so starting and stoping it won't clear its events.
more than that since the original event or callback are never saved there is no real option to the individual implementations to have a proper `stop` method without overriding the `start` method.

**Comment by arb** [comment]
Yes, it is up to implementors to bind to listen events if the default behavior in `start` isn't enough for them. [good-file](https://github.com/hapijs/good-file/blob/master/lib/index.js#L128) does this for example. So if you need to overwrite `stop`, you will likely need to overwrite `start` as well. The `callback` being passed in is just to indicate that startup of this report has completed, not indicating that an even has been reporter. good-console doesn't implement stop because there isn't anything for it to do. There isn't any cleanup to run.

I'm not sure I'm following what your issue here is... that being said, this repo is going away in the not-too-distant-future so I don't think it's worth any time investment to change how it functions.
